accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'


urlpatterns = [
    url(r'^list/$', views.accounts_list, name='list'),
    url(r'^create/$', views.add_account, name='new_account'),
    url(r'^(?P<account_id>\d*)/view/$', views.view_account, name="view_account"),
    url(r'^(?P<edid>\d*)/edit/$', views.edit_account, name="edit_account"),
    url(r'^(?P<aid>\d*)/delete/$', views.remove_account, name="remove_account"),
    url(r'^get/list/$', views.get_accounts, name='get_accounts'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

contacts/urls.py
from django.conf.urls import url
from contacts import views

app_name = 'contacts'


urlpatterns = [
    url(r'^list/$', views.contacts_list, name='list'),
    url(r'^create/$', views.add_contact, name='add_contact'),
    url(r'^(?P<contact_id>\d+)/view/$', views.view_contact, name='view_contact'),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_contact, name='edit_contact'),
    url(r'^(?P<pk>\d+)/delete/$', views.remove_contact, name='remove_contact'),
    url(r'^get/list/$', views.get_contacts, name='get_contacts'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings

app_name = 'crm'


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^leads/', include('leads.urls', namespace='leads')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^oppurtunities/', include('oppurtunity.urls', namespace='oppurtunities')),
    url(r'^cases/', include('cases.urls', namespace='cases')),
    url(r'^quotations/', include('quotations.urls', namespace='quotations')),
    url(r'^excel/', include('excel.urls', namespace='excel')),
    # url(r'^emails/', include('emails.urls', namespace='emails')),
    # url(r'^planner/', include('planner.urls', namespace='planner')),
    url(r'^logout/$', views.logout, {'next_page': '/login/'}, name='logout'),

]
'''
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
'''

oppurtunity/urls.py
from django.conf.urls import url
from oppurtunity import views

app_name = 'oppurtunity'


urlpatterns = [
    url(r'^list/$', views.opp_list, name='list'),
    url(r'^create/$', views.opp_create, name='save'),
    url(r'^(?P<pk>\d+)/view/$', views.opp_view, name='opp_view'),
    url(r'^(?P<pk>\d+)/edit/$', views.opp_edit, name='opp_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.opp_remove, name='opp_remove'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^get/list/$', views.get_opportunity, name='get_opportunity'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

from common.utils import COUNTRIES


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def __unicode__(self):
        return self.email


class Address(models.Model):
    address_line = models.CharField(_("Address"), max_length=255, blank=True, null=True)
    street = models.CharField(_("Street"), max_length=55, blank=True, null=True)
    city = models.CharField(_("City"), max_length=255, blank=True, null=True)
    state = models.CharField(_("State"), max_length=255, blank=True, null=True)
    postcode = models.CharField(_("Post/Zip-code"), max_length=64, blank=True, null=True)
    country = models.CharField(max_length=3, choices=COUNTRIES, blank=True, null=True)

    def __str__(self):
        return self.city


class Team(models.Model):
    name = models.CharField(max_length=55)
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Comment(models.Model):
    case = models.ForeignKey('cases.Case', blank=True, null=True, related_name="cases", on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    commented_on = models.DateTimeField(auto_now_add=True)
    commented_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    account = models.ForeignKey(
        'accounts.Account', blank=True, null=True, related_name="accounts_comments", on_delete=models.CASCADE)
    lead = models.ForeignKey('leads.Lead', blank=True, null=True, related_name="leads", on_delete=models.CASCADE)
    opportunity = models.ForeignKey(
        'oppurtunity.Opportunity', blank=True, null=True, related_name="opportunity_comments", on_delete=models.CASCADE)
    contact = models.ForeignKey(
        'contacts.Contact', blank=True, null=True, related_name="contact_comments", on_delete=models.CASCADE)

    def get_files(self):
        return Comment_Files.objects.filter(comment_id=self)


class Comment_Files(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now_add=True)
    comment_file = models.FileField("File", upload_to="comment_files", default='')

    def get_file_name(self):
        if self.comment_file:
            return self.comment_file.path.split('/')[-1]
        else:
            return None

oppurtunity/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _

from accounts.models import Account
from contacts.models import Contact
from common.models import User, Team
from common.utils import STAGES, SOURCES, CURRENCY_CODES


class Opportunity(models.Model):
    name = models.CharField(pgettext_lazy("Name of Opportunity", "Name"), max_length=64)
    account = models.ForeignKey(Account, related_name='opportunities', on_delete=models.CASCADE, blank=True, null=True)
    stage = models.CharField(
        pgettext_lazy("Stage of Opportunity", "Stage"), max_length=64, choices=STAGES)
    currency = models.CharField(max_length=3, choices=CURRENCY_CODES, blank=True, null=True)
    amount = models.DecimalField(_("Opportunity Amount"), decimal_places=2, max_digits=12, blank=True, null=True)
    lead_source = models.CharField(_("Source of Lead"), max_length=255, choices=SOURCES, blank=True, null=True)
    probability = models.IntegerField(default=0, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    closed_on = models.DateTimeField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='opportunity_assigned_to')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='opportunity_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

oppurtunity/forms.py
from django import forms
from oppurtunity.models import Opportunity
from common.models import Comment


class OpportunityForm(forms.ModelForm):
    probability = forms.IntegerField(max_value=100, required=False)

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        opp_accounts = kwargs.pop('account', [])
        opp_contacts = kwargs.pop('contacts', [])
        super(OpportunityForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['description'].widget.attrs.update({
            'rows': '8'})
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['account'].queryset = opp_accounts
        self.fields['contacts'].queryset = opp_contacts
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False
        self.fields['contacts'].required = False

    class Meta:
        model = Opportunity
        fields = (
            'name', 'amount', 'account', 'contacts', 'assigned_to', 'currency',
            'probability', 'teams', 'closed_on', 'lead_source', 'description', 'stage',
        )


class OpportunityCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'opportunity', 'commented_by')

templates/oppurtunity/opp_contacts.html
<select>
{% for cont in con %}
	<option value="{{cont.id}}" {% for sel in selcon %} {% ifequal cont.id sel.id %} selected {% endifequal%}{% endfor %}>{{cont.name}}</option>
{% endfor %}
</select>

templates/oppurtunity/opportunities_list.html
<table class="table">
  <thead>
    <tr>
      <th width="50%">
        <a href='#'>
        Name
        </a>
        <span class="caret"></span>
      </th>
      <th>
        <a href="#">
        Stage
        </a>
      </th>
    </tr>
  </thead>
  <tbody>
    {% ifequal opportunities|length  0 %}
    <tr>
      <td class="cell">
        NO OPPORTUNITIES FOUND!!
      </td>
    </tr>
    {% endifequal %}
    {% for opportunity in opportunities %}
    <tr>
      <td class="cell">
        <a class="cell parentname" id="{{ opportunity.id }}">
        {{ opportunity.name }}
        </a>
      </td>
      <td class="cell parentstage">
        {{ opportunity.stage }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

templates/oppurtunity/opportunity.html
{% extends "base.html" %}
{% load staticfiles %}
{% load paginate %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- heading_create starts here -->
  <div class="row marl heading_create">
    <div class="heading col-md-12">
      <div class="col-md-6">
        <h4>Opportunities</h4>
      </div>
      <div class="col-md-6">
        <div class="create_new text-right">
          <a href="{% url 'oppurtunities:save' %}"><i class="fa fa-plus"></i> Add New Opportunity</a>
        </div>
      </div>
    </div>
  </div>
  <!-- heading_create ends here -->
  <!-- filter_row starts here -->
  <div class="filter_row row marl">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
        </div>
        <form id="opportunity_filter" method="POST" action="">{% csrf_token %}
          <div class="panel-content text-center">
            <div class="filter_col col-md-3">
              <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" placeholder="Name" id="id_name" name="name" {% if request.POST %} value="{{request.POST.name}}" {% endif %}>
              </div>
            </div>
            <div class="filter_col col-md-3">
              <div class="form-group">
                <label for="exampleInputEmail1">Account</label>
                <select class="form-control" id="id_account" name="account">
                  <option value="">---------</option>
                  {% for l in accounts %}
                  <option value="{{l.id}}" {% if request.POST.account %}{%ifequal l.id request.POST.account|add:"0"%}selected{%endifequal%} {% endif %}>{{ l.name }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="filter_col col-md-3">
              <div class="form-group">
                <label for="exampleInputEmail1">Stage</label>
                <select class="form-control" id="id_stage" name="stage" >
                  <option value="">---------</option>
                  {% for stage in stages %}
                  <option value="{{stage.0}}" {% if request.POST.stage %} {% ifequal stage.0 request.POST.stage %}selected{% endifequal %} {% endif %}>{{stage.1}} </option>
                  {% endfor%}
                </select>
              </div>
            </div>
            <div class="filter_col col-md-3">
              <div class="form-group">
                <label for="exampleInputEmail1">Lead Source</label>
                <select class="form-control" id="id_lead_source" name="lead_source" >
                  <option value="">---------</option>
                  {% for source in sources %}
                  <option value="{{source.0}}" {% if request.POST.lead_source %} {% ifequal source.0 request.POST.lead_source %}selected{% endifequal %} {% endif %}>{{source.1}} </option>
                  {% endfor%}
                </select>
              </div>
            </div>
            <div class="filter_col text-center">
              <div class="form-group">
                <button class="btn btn-primary" type="submit">Search</button>
                <a href="{% url 'oppurtunities:list' %}" class="btn btn-default">Clear</a>
              </div>
            </div>
          </div>
        </form>
        <br clear="all">
      </div>
    </div>
  </div>
  <!-- filter_row ends here -->
  <!-- opportunities list start-->
  <div class="table_container_row row marl">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading-list text-center">
          LIST OF OPPORTUNITIES
          <span class="pull-right total_count">{% if show_pageitems %} {% show_pageitems %}{% else %}Total Opportunities {{ opportunity_list|length }}{% endif %}</span>
        </div>
        <div class="panel-content">
          <table class="table table-bordered table-striped table-condensed">
            <thead>
              <tr>
                <th width="5%" style="text-align:center;">S.No</th>
                <th width="15%" style="text-align:center;">Name</th>
                <th width="15%" style="text-align:center;">Account</th>
                <th width="15%" style="text-align:center;">Contact(s)</th>
                <th width="15%" style="text-align:center;">Stage</th>
                <th width="10%" style="text-align:center;">Lead Source</th>
                <th width="25%" style="text-align:center;">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% if per_page %}
                {% paginate per_page opportunity_list %}
              {% else %}
                {% paginate 10 opportunity_list %}
              {% endif %}
              {% for opportunity in opportunity_list %}
              <tr class="text-center">
                <td scope="row">{{ forloop.counter }}</td>
                <td><a href="{% url  'oppurtunities:opp_view' opportunity.id %}">{{ opportunity.name }}</a></td>
                <td>
                  {% if opportunity.account %}
                    <a href="{% url  'accounts:view_account' opportunity.account.id %}">{{ opportunity.account }}</a>
                  {% else %}
                    No Related Account
                  {% endif %}
                </td>
                <td>
                  {% with opp_contacts=opportunity.contacts.all %}
                    {% if opp_contacts %}
                      {% for contact in opp_contacts %}
                        <li class="text-left"><a href="{% url 'contacts:view_contact' contact.id %}">{{contact.first_name}} {{contact.last_name}}</a></li>
                      {% endfor %}
                    {% else %}
                      No Related Contact
                    {% endif %}
                  {% endwith %}
                </td>
                <td>{% if opportunity.stage %}{{ opportunity.stage }}{% else %}Not Specified {% endif %}</td>
                <td>{% if opportunity.lead_source %}{{ opportunity.lead_source }}{% else %}Not Specified{% endif %}</td>
                <td>
                  <a href="{% url 'oppurtunities:opp_view' opportunity.id %}" class="btn btn-info ">View</a>
                  <a href="{% url 'oppurtunities:opp_edit' opportunity.id %}" class="btn btn-success ">Edit</a>
                  <a href="{% url 'oppurtunities:opp_remove' opportunity.id %}" class="btn btn-danger delete">Delete</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          {% ifequal opportunity_list|length 0 %}
            <h4 class="text-center">No Opportunity Records Found</h4>
          {% endifequal %}
          <div class="marl row text-center">
            {% show_pages %}
          </div>
        </div>
      </div>
    </div>
    <br clear="all">
  </div>
  <!-- opportunities list end-->
</div>
<!-- main_container ends here -->
{% endblock %}
{% block js_block %}
<script type="text/javascript">
  $('.delete').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });

  $("a[rel='page']").click(function(e){
    e.preventDefault();
    $('#opportunity_filter').attr("action", $(this).attr("href"));
    $('#opportunity_filter').submit();
  });
</script>
{% endblock js_block %}

templates/oppurtunity/opportunity_comments.html
{% for comment in comments %}
<li class="list-group-item list-row" id="comment{{comment.id}}">
  <div class="pull-right right-container">
    <div class="list-row-buttons btn-group pull-right">
      <button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" type="button"><span class="caret"></span></button>
      <ul class="dropdown-menu pull-right">
      <li>
      <a href="{% url 'comment_remove' pk=comment.pk %}"><button type="submit">Submit</button></a>
        <span class="glyphicon glyphicon-remove"></span></a>
      </li>
      </ul>
    </div>
  </div>
  <div class="stream-head-container">{{comment.comment_person}} Commented</div>
  <div class="stream-post-container" id="comment_name{{comment.id}}">{{comment.comment}}</div>
  <div class="stream-date-container">{{comment.comment_time}}</div>
  {% endfor %}

templates/oppurtunity/view_opportunity.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb1 %}
<!-- Breadcrumb Starts Here -->
  <ol class="breadcrumb">
    <li><a href="{% url 'oppurtunities:list' %}">OPPORTUNITIES</a></li>
    <li class="active">VIEW</li>
  </ol>
<!-- Breadcrumb Ends Here -->
{% endblock%}
{% block content%}
<!-- OPPORTUNITY VIEW STARTS -->
  <div class="main_container" id="maincontainer">
    <div class="overview_form_block row marl">
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading view-pad">
            <h5>
              OVERVIEW
              <span class="pull-right" style="margin-top: -10px">
                <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Actions
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'oppurtunities:opp_edit' opportunity_record.id %}" >Edit</a></li>
                    <li class="delete_contact"><a href="{% url 'oppurtunities:opp_remove' opportunity_record.id %}" id="remove_contact">REMOVE</a></li>
                  </ul>
                </div>
              </span>
            </h5>
          </div>
          <div class="panel-content" id="datashow">
            <div class="row marl">
              <div class="col-md-6">
                <div class="filter_col col-md-12" id="iname">
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_name" data-name="name">Name</label>
                    <div class="opportunity_field" id="opportunity_name" data-name="name">{{ opportunity_record.name }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_opportunity_account" data-name="name">Account</label>
                    <div class="opportunity_field" id ="opportunity_account" data-name="name">{{ opportunity_record.account }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  {% if opportunity_record.contacts.all %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_contact" data-name="name">Contact(s)</label>
                    <div class="opportunity_field" id="opportunity_contact" data-name="name">
                      {% for contact in opportunity_record.contacts.all %}
                        <li>{{ contact }}</li>
                      {% endfor %}
                    </div>
                  </div>
                  {% endif %}
                </div>
                <div class="filter_col col-md-12">
                  {% if opportunity_record.amount %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_amount" data-name="name">Amount</label>
                    <div class="opportunity_field" id="opportunity_amount" data-name="name">{{ opportunity_record.currency }} {{ opportunity_record.amount }}</div>
                  </div>
                  {% endif %}
                </div>
              </div>
              <div class="col-md-4">
                <div class="filter_col col-md-12">
                  {% if opportunity_record.stage %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_stage" data-name="name">Stage</label>
                    <div class="opportunity_field" id="opportunity_stage" data-name="name">{{ opportunity_record.stage }}</div>
                  </div>
                  {% endif %}
                </div>
                <div class="filter_col col-md-12">
                  {% if opportunity_record.lead_source %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_lead_source" data-name="name">Lead Source</label>
                    <div class="opportunity_field" id="opportunity_lead_source" data-name="name">{{ opportunity_record.lead_source }}</div>
                  </div>
                  {% endif %}
                </div>
                <div class="filter_col col-md-12">
                  {% if opportunity_record.probability %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_probability" data-name="name">Probability</label>
                    <div class="opportunity_field" id="opportunity_probability" data-name="name">{{opportunity_record.probability}} %</div>
                  </div>
                  {% endif %}
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_close_date" data-name="name">Close Date</label>
                    <div class="opportunity_field" id="opportunity_close_date" data-name="name">{{opportunity_record.closed_on|date}}</div>
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <div class="filter_col col-md-12">
                  {% if opportunity_record.description %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_description" data-name="name">Description</label>
                    <div class="opportunity_field" id="opportunity_description" data-name="name">{{opportunity_record.description}}</div>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          <!-- Comments Section starts-->
          <div class="panel-heading view-pad">
            <h5>COMMENTS</h5>
          </div>
          <div class="panel-content" id="datashow">
            <div class="row marl">
              <div class="col-md-12">
                <form id="comment_form" method="POST" enctype="multipart/form-data">{% csrf_token %}
                  <div class="form-group">
                    <textarea class="form-control" textarea cols="40" rows="3" id="id_comments" name="comment" placeholder="Submit Your Comments Here"></textarea><span><i id="CommentError" style="display:none; color:red"></i></span>
                    </br>
                    <button class="btn btn-default save" style="text-align: center;" id="comment_submit" type="submit">Submit</button>
                  </div>
                  <input type="hidden" value="{{ opportunity_record.id }}" name="opportunityid">
                </form>
                <ul class="list-group" id="comments_div">
                  {% for comment in comments %}
                  <li class="list-group-item list-row" id="comment{{comment.id}}">
                    <div class="pull-right right-container">
                      <div class="list-row-buttons btn-group pull-right">
                        <button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" type="button"><span class="caret"></span></button>
                        <ul class="dropdown-menu pull-right">
                          <li>
                            <a class="action" onclick="edit_comment({{comment.id}})">Edit</a>
                          </li>
                          <li>
                            <a class="action" onclick="remove_comment({{comment.id}})">Remove</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="stream-head-container">{{ comment.commented_by }} Commented</div>
                    <div class="stream-post-container" id="comment_name{{comment.id}}"><pre>{{ comment.comment }}</pre></div>
                    <div class="stream-date-container">{{ comment.commented_on }}</div>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            <div class="modal fade" id="Comments_Opportunity_Modal" role="dialog" data-keyboard="false" data-backdrop="static">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Update Your Comment</h4>
                  </div>
                  <form id="comment_edit_form" method="POST" >{% csrf_token %}
                    <div class="modal-body">
                      <div class="form-group">
                        <textarea class="form-control" textarea cols="40" rows="3" id="id_editcomment" name="comment" placeholder="Submit Your Comments"></textarea>
                        <input type="hidden" value="{{ opportunity.id }}" name="opportunityid">
                        <input type="hidden" value="" name="commentid" id="commentid">
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button class="btn btn-default save" id="comment_edit" type="submit">Update</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <!-- Comments Section Ends-->
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading view-pad">
            <h5>Label</h5>
          </div>
          <div class="panel-content" id="datashow">
            <div class="row marl">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="opportunity_field_label" for="id_assigned_user" data-name="name">Assigned User(s)</label>
                  <div class="opportunity_field" id="opportunity_assigned_users" data-name="name">
                    {%if not opportunity_record.assigned_to %}
                      Not Assigned Yet
                    {% else %}
                      {% for user in opportunity_record.assigned_to.all %}
                        <li>{{ user }}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="opportunity_field_label" for="id_team" data-name="name">Assigned Team(s)</label>
                  <div class="opportunity_field" id="opportunity_team" data-name="name">
                    {%if not opportunity_record.teams %}
                      Not Assigned Yet
                    {% else %}
                      {% for team in opportunity_record.teams.all %}
                        <li>{{ team }}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="opportunity_field_label" for="id_created_on" data-name="name">Created On</label>
                  <div class="opportunity_field" id="opportunity_created_on" data-name="name">{{opportunity_record.created_on}}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="opportunity_field_label" for="id_created_by" data-name="name">Created by</label>
                  <div class="opportunity_field" id="opportunity_created_by" data-name="name">{{opportunity_record.created_by}}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- OPPORTUNITY VIEW ENDS -->
{% endblock %}
{% block js_block %}
<script src="{% static 'js/opportunities/view_opportunity.js' %}"></script>
<script type="text/javascript">
  $(function () {
      $('#datetimepicker1').datetimepicker({
          'format': 'YYYY-MM-DD',
      });
  });
</script>
{% endblock js_block %}