accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'


urlpatterns = [
    url(r'^list/$', views.accounts_list, name='list'),
    url(r'^create/$', views.add_account, name='new_account'),
    url(r'^(?P<account_id>\d*)/view/$', views.view_account, name="view_account"),
    url(r'^(?P<edid>\d*)/edit/$', views.edit_account, name="edit_account"),
    url(r'^(?P<aid>\d*)/delete/$', views.remove_account, name="remove_account"),
    url(r'^get/list/$', views.get_accounts, name='get_accounts'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

cases/urls.py
from django.conf.urls import url
from cases import views

app_name = 'cases'


urlpatterns = [
    url(r'^list/$', views.cases_list, name='list'),
    url(r'^create/$', views.add_case, name='add_case'),
    url(r'^(?P<case_id>\d+)/view/$', views.view_case, name='view_case'),
    url(r'^(?P<case_id>\d+)/edit_case/$', views.edit_case, name='edit_case'),
    url(r'^close_case/$', views.close_case, name="close_case"),
    url(r'^(?P<case_id>\d+)/remove/$', views.remove_case, name='remove_case'),
    url(r'^select_contacts/$', views.selectContacts, name="select_contacts"),
    url(r'^get/list/$', views.get_cases, name='get_cases'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings

app_name = 'crm'


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^leads/', include('leads.urls', namespace='leads')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^oppurtunities/', include('oppurtunity.urls', namespace='oppurtunities')),
    url(r'^cases/', include('cases.urls', namespace='cases')),
    url(r'^quotations/', include('quotations.urls', namespace='quotations')),
    url(r'^excel/', include('excel.urls', namespace='excel')),
    # url(r'^emails/', include('emails.urls', namespace='emails')),
    # url(r'^planner/', include('planner.urls', namespace='planner')),
    url(r'^logout/$', views.logout, {'next_page': '/login/'}, name='logout'),

]
'''
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
'''

cases/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from accounts.models import Account
from contacts.models import Contact
from common.models import User, Team
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE


class Case(models.Model):
    name = models.CharField(
        pgettext_lazy("Name of the case", "Name"),
        max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(choices=CASE_TYPE, max_length=255, blank=True, null=True, default='')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_on = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='case_assigned_users')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='case_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting", status="Planned")

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting").exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Task", status="Planned")

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task").exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Call", status="Planned")

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call").exclude(status="Planned")

    def get_assigned_user(self):
        return User.objects.get(id=self.assigned_to.id)

cases/forms.py
from django import forms
from cases.models import Case
from common.models import Comment


class CaseForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        case_accounts = kwargs.pop('account', [])
        case_contacts = kwargs.pop('contacts', [])
        super(CaseForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['description'].widget.attrs.update({
            'rows': '6'})
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['account'].queryset = case_accounts
        self.fields['contacts'].queryset = case_contacts
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False
        self.fields['contacts'].required = False

    class Meta:
        model = Case
        fields = ('assigned_to', 'teams', 'name', 'status',
                  'priority', 'case_type', 'account',
                  'contacts', 'closed_on', 'description')

    def clean_name(self):
        name = self.cleaned_data['name']
        case = Case.objects.filter(name__iexact=name).exclude(id=self.instance.id)
        if case:
            raise forms.ValidationError("Case Already Exists with this Name")
        return name


class CaseCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'case', 'commented_by', )

cases/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, reverse
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from cases.models import Case
from cases.forms import CaseForm, CaseCommentForm
from common.models import Team, User, Comment
from accounts.models import Account
from contacts.models import Contact
from common.utils import PRIORITY_CHOICE, STATUS_CHOICE, CASE_TYPE

# CRUD Operations Start


@login_required
def cases_list(request):
    cases = Case.objects.all().select_related("account")
    accounts = Account.objects.all()
    page = request.POST.get('per_page')
    name = request.POST.get('name')
    status = request.POST.get('status')
    priority = request.POST.get('priority')
    account = request.POST.get('account')
    if not account:
        account = 0
    if name:
        cases = Case.objects.filter(name__contains=name)
    if account:
        cases = cases.filter(account=account)
    if status:
        cases = cases.filter(status=status)
    if priority:
        cases = cases.filter(priority=priority)
    return render(request, "cases/cases.html", {
        'cases': cases,
        'accounts': accounts,
        'acc': int(account),
        'per_page': page,
        'case_priority': PRIORITY_CHOICE,
        'case_status': STATUS_CHOICE
    })


@login_required
def add_case(request):
    accounts = Account.objects.all()
    contacts = Contact.objects.all()
    users = User.objects.filter(is_active=True).order_by('email')
    form = CaseForm(assigned_to=users, account=accounts, contacts=contacts)
    teams = Team.objects.all()
    teams_list = request.POST.getlist("teams")
    assignedto_list = request.POST.getlist("assigned_to")
    contacts_list = request.POST.getlist("contacts")
    if request.method == 'POST':
        form = CaseForm(request.POST, assigned_to=users, account=accounts, contacts=contacts)
        if form.is_valid():
            case = form.save(commit=False)
            case.created_by = request.user
            case.save()
            case.assigned_to.add(*assignedto_list)
            case.teams.add(*teams_list)
            case.contacts.add(*contacts_list)
            if request.is_ajax():
                return JsonResponse({'error': False})
            if request.POST.get("savenewform"):
                return redirect("cases:case_add")
            else:
                return HttpResponseRedirect(reverse('cases:list'))
        else:
            if request.is_ajax():
                return JsonResponse({'error': True, 'case_errors': form.errors})
            return render(request, "cases/create_cases.html", {
                'case_form': form,
                'accounts': accounts,
                'users': users,
                'teams': teams,
                'case_types': CASE_TYPE,
                'case_priority': PRIORITY_CHOICE,
                'case_status': STATUS_CHOICE,
                'teams_list': teams_list,
                'assignedto_list': assignedto_list,
                'contacts_list': contacts_list
            })
    return render(request, "cases/create_cases.html", {
        'case_form': form,
        'accounts': accounts,
        'users': users,
        'teams': teams,
        'teams_list': teams_list,
        'assignedto_list': assignedto_list,
        'contacts_list': contacts_list,
        'case_types': CASE_TYPE,
        'case_priority': PRIORITY_CHOICE,
        'case_status': STATUS_CHOICE
    })


@login_required
def view_case(request, case_id):
    case_record = get_object_or_404(
        Case.objects.prefetch_related("contacts", "account"), id=case_id)
    comments = case_record.cases.all()
    return render(request, "cases/view_case.html", {
        'case_record': case_record,
        'comments': comments
    })


@login_required
def edit_case(request, case_id):
    case_object = get_object_or_404(Case, id=case_id)
    users = User.objects.filter(is_active=True).order_by('email')
    accounts = Account.objects.all()
    contacts = Contact.objects.all()
    form = CaseForm(instance=case_object, assigned_to=users, account=accounts, contacts=contacts)
    teams = Team.objects.all()
    teams_list = request.POST.getlist("teams")
    assignedto_list = request.POST.getlist("assigned_to")
    contacts_list = request.POST.getlist("contacts")
    if request.method == 'POST':
        form = CaseForm(
            request.POST, instance=case_object, assigned_to=users, account=accounts,
            contacts=contacts
        )
        if form.is_valid():
            case_obj = form.save(commit=False)
            if request.POST.get("account"):
                case_obj.account = Account.objects.get(id=request.POST.get("account"))
            case_obj.created_by = request.user
            case_obj.save()
            case_obj.assigned_to.clear()
            case_obj.assigned_to.add(*assignedto_list)
            case_obj.teams.clear()
            case_obj.teams.add(*teams_list)
            case_obj.contacts.clear()
            case_obj.contacts.add(*contacts_list)
            if request.is_ajax():
                return JsonResponse({'error': False})
            return HttpResponseRedirect(reverse('cases:list'))
        else:
            if request.is_ajax():
                return JsonResponse({'error': True, 'case_errors': form.errors})
            return render(request, "cases/create_cases.html", {
                'case_obj': case_object,
                'case_form': form,
                'accounts': accounts,
                'users': users,
                'teams': teams,
                'case_types': CASE_TYPE,
                'case_priority': PRIORITY_CHOICE,
                'case_status': STATUS_CHOICE,
                'teams_list': teams_list,
                'assignedto_list': assignedto_list,
                'contacts_list': contacts_list
            })

    return render(request, "cases/create_cases.html", {
        'case_form': form,
        'case_obj': case_object,
        'accounts': accounts,
        'users': users,
        'teams': teams,
        'case_types': CASE_TYPE,
        'case_priority': PRIORITY_CHOICE,
        'case_status': STATUS_CHOICE,
        'assignedto_list': assignedto_list,
        'teams_list': teams_list,
        'contacts_list': contacts_list
    })


@login_required
def remove_case(request, case_id):
    if request.method == 'POST':
        cid = request.POST['case_id']
        get_object_or_404(Case, id=cid).delete()
        count = Case.objects.filter(Q(assigned_to=request.user) | Q(created_by=request.user)).count()
        data = {"case_id": cid, "count": count}
        return JsonResponse(data)
    else:
        Case.objects.filter(id=case_id).delete()
        return HttpResponseRedirect(reverse('cases:list'))


@login_required
def close_case(request):
    cid = request.POST['case_id']
    case = get_object_or_404(Case, id=cid)
    case.status = "Closed"
    case.save()
    data = {'status': "Closed", "cid": cid}
    return JsonResponse(data)


def selectContacts(request):
    contact_account = request.GET.get("account")
    if contact_account:
        account = get_object_or_404(Account, id=contact_account)
        contacts = Contact.objects.filter(account=account)
    else:
        contacts = Contact.objects.all()
    data = {}
    for i in contacts:
        new = {i.pk: i.first_name}
        data.update(new)
    return JsonResponse(data)


# CRUD Operations End
# Comments Section Start


@login_required
def add_comment(request):
    if request.method == 'POST':
        case = get_object_or_404(Case, id=request.POST.get('caseid'))
        if request.user in case.assigned_to.all() or request.user == case.created_by:
            form = CaseCommentForm(request.POST)
            if form.is_valid():
                case_comment = form.save(commit=False)
                case_comment.comment = request.POST.get('comment')
                case_comment.commented_by = request.user
                case_comment.case = case
                case_comment.save()
                data = {"comment_id": case_comment.id, "comment": case_comment.comment,
                        "commented_on": case_comment.commented_on,
                        "commented_by": case_comment.commented_by.email}
                return JsonResponse(data)
            else:
                return JsonResponse({"error": form['comment'].errors})
        else:
            data = {'error': "You Dont Have permissions to Comment"}
            return JsonResponse(data)


@login_required
def edit_comment(request):
    if request.method == "POST":
        comment = request.POST.get('comment')
        comment_id = request.POST.get("commentid")
        comment_obj = get_object_or_404(Comment, id=comment_id)
        form = CaseCommentForm(request.POST)
        if request.user == comment_obj.commented_by:
            if form.is_valid():
                comment_obj.comment = comment
                comment_obj.save()
                data = {"comment": comment_obj.comment, "commentid": comment_id}
                return JsonResponse(data)
            else:
                return JsonResponse({"error": form['comment'].errors})
        else:
            return JsonResponse({"error": "You dont have authentication to edit"})
    else:
        return render(request, "404.html")


@login_required
def remove_comment(request):
    if request.method == 'POST':
        comment_id = request.POST.get('comment_id')
        comment = get_object_or_404(Comment, id=comment_id)
        if request.user == comment.commented_by:
            comment.delete()
            data = {"cid": comment_id}
            return JsonResponse(data)
        else:
            return JsonResponse({"error": "You Dont have permisions to delete"})
    else:
        return HttpResponse("Something Went Wrong")


# Comments Section End
# Other Views


@login_required
def get_cases(request):

templates/cases/cases.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- heading_create starts here -->
  <div class="row marl heading_create">
    <div class="heading col-md-12">
      <div class="col-md-6">
        <h4>Cases</h4>
      </div>
      <div class="col-md-6">
        <div class="create_new text-right">
          <a href="{% url 'cases:add_case' %}"><i class="fa fa-plus"></i>Add New Case</a>
        </div>
      </div>
    </div>
  </div>
  <!-- heading_create ends here -->
  <!-- filter_row starts here -->
  <div class="filter_row row marl">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
        </div>
        <form id="cases_filter" method="POST" action="" >{% csrf_token %}
          <div class="panel-content">
            <div class="filter_col col-md-3">
              <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" class="form-control" placeholder="Name" name="name" value="{{request.POST.name}}">
              </div>
            </div>
            <div class="filter_col col-md-3">
              <div class="form-group">
                <label for="exampleInputEmail1">Status</label>
                <select class="form-control" id="id_status" name="status" >
                  <option value="">--Status--</option>
                  {% for each_status in case_status %}
                  <option value="{{each_status.0}}" {% if request.POST.status %} {% ifequal each_status.0 request.POST.status %}selected{% endifequal %}{% endif %} >{{each_status.1}} </option>
                  {% endfor%}
                </select>
              </div>
            </div>
            <div class="filter_col col-md-3">
              <div class="form-group">
                <label for="exampleInputEmail1">Priority</label>
                <select class="form-control" id="id_priority" name="priority" >
                  <option value="">--Priority--</option>
                  {% for each_priority in case_priority %}
                  <option value="{{each_priority.0}}" {% if request.POST.priority %} {% ifequal each_priority.0 request.POST.priority %}selected{% endifequal %}{% endif %}>{{each_priority.1}} </option>
                  {% endfor%}
                </select>
              </div>
            </div>
            <div class="filter_col col-md-3">
              <div class="form-group">
                <label for="exampleInputEmail1">Account</label>
                <select class="form-control" id="id_account" name="account">
                  <option value="">--Select Account--</option>
                  {% for ac in accounts %}
                  <option value="{{ac.id}}" {% ifequal acc ac.id %} selected {% endifequal %} >{{ac.name}}</option>
                  {% endfor %}
                </select>
                </select>
              </div>
            </div>
            <input type="hidden" id="per_page_field" name="per_page">
            <div class="filter_col text-center">
              <div class="form-group">
                <button class="btn btn-primary" id="filter_click" type="submit">Search</button>
                <a href="{% url 'cases:list' %}" id="filter_clear" class="btn btn-default">Clear</a>
              </div>
            </div>
          </div>
        </form>
        <br clear="all">
        </div>
      </div>
    </div>
  </div>
  <!-- filter_row ends here -->
  <!-- cases_list starts here -->
  <div class="table_container_row row marl">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading-list text-center">
          LIST OF CASES
          <span class="pull-right total_count">{% if show_pageitems %} {% show_pageitems %}{% else %}Total Cases {{ cases|length }}{% endif %}</span>
        </div>
        <div class="panel-content">
          <table class="table table-bordered table-striped table-condensed" id="multiselect">
            <thead>
              <tr>
                <th width="5%" style="text-align:center;">S.No</th>
                <th width="20%" style="text-align:center;">Name</th>
                <th width="20%" style="text-align:center;">Account</th>
                <th width="15%" style="text-align:center;">Status</th>
                <th width="15%" style="text-align:center;">Priority</th>
                <th width="25%" style="text-align:center;">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% if per_page %}
                {% paginate per_page cases %}
              {% else%}
                {% paginate 10 cases%}
              {% endif %}
              {% for case in cases %}
              <tr class="case_row{{case.id}}" style="text-align:center;">
                <td scope="row">{{ forloop.counter }}</td>
                <td><a href="{% url 'cases:view_case' case.id %}">{{ case.name }}</a></td>
                <td>
                  {% if case.account %}
                    <a href="{% url  'accounts:view_account' case.account.id %}">{{ case.account }}</a>
                  {% else %}
                    No Related Account
                  {% endif %}
                </td>
                <td id="status_id{{case.id}}" status="{{case.status}}">{{ case.status }}</td>
                <td>{{ case.priority }}</td>
                <td>
                  <a href="{% url 'cases:view_case' case.id %}" class="btn btn-info">View</a>
                  <a href="{% url 'cases:edit_case' case.id %}" class="btn btn-success">Edit</a>
                  <a onclick="remove_case({{case.id}}, '{% url 'cases:remove_case' case.id %}')" class="btn btn-danger">Remove</a>
                  <a onclick="close_case({{case.id}}, '{% url 'cases:close_case' %}')" class="btn btn-warning">Close</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          {% ifequal cases|length 0 %}
            <h4 class="text-center">No Cases Records Found</h4>
          {% endifequal %}
          <div class="marl row text-center">
            {% show_pages %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- cases_list ends here -->
</div>
<!-- main_container ends here -->
{% endblock %}
{% block js_block %}
  <script src="{% static 'js/cases/cases.js' %}"></script>
{% endblock js_block %}

templates/cases/cases_list.html
<table class="table">
    <thead>
    <tr>
        <th width="50%">
            <a href='#'>
                Name
            </a>
            <span class="caret"></span>
        </th>
        <th>
            <a href="#">
                Status
            </a>
        </th>
    </tr>
    </thead>
    <tbody>
    {% ifequal cases|length  0 %}
     <tr>
         <td class="cell">
         NO CASES FOUND!!
         </td>
     </tr>
    {% endifequal %}
    {% for case in cases %}
    <tr>
        <td class="cell">
            <a class="cell parentname" id="{{ case.id }}">
                {{ case.name }}
            </a>
        </td>
        <td class="cell parentstatus">
            {{ case.status }}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

templates/cases/comments.html
{% for comment in comments %}
<li class="list-group-item list-row" id="comment{{comment.id}}">
  <div class="pull-right right-container">
    <div class="list-row-buttons btn-group pull-right">
      <button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" type="button"><span class="caret"></span></button>
      <ul class="dropdown-menu pull-right">
        <li>
          <a class="action" onclick="edit_comment({{comment.id}})" >Edit</a>
        </li>
        <li>
          <a class="action" onclick="remove_comment({{comment.id}})">Remove</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="stream-head-container">{{comment.comment_user}} Commented</div>
  <div class="stream-post-container" id="comment_name{{comment.id}}">{{comment.comment}}</div>
  <div class="stream-date-container">{{comment.comment_time}}</div><span>{%if comment.get_file%}<a href="file:////home/raghu/Documents/Jango/CRM/crm_proj/media/{{comment.comment_file}}">{{comment.get_file}}</a>{% endif %}</span>
  {% endfor %}

templates/cases/create_cases.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
  <ol class="breadcrumb">
    <li><a href="#">Cases</a></li>
    <li class="active">Create</li>
  </ol>
{% endblock %}
{% block content %}
  <form id="submitForm" method="POST" action="" novalidate>{% csrf_token %}
    <div class="assigned_teams row marl">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Assigned Users & Teams
          </div>
          <div class="panel-content">
            <div class="filter_col col-md-6">
              <div class="form-group">
                <label for="exampleInputEmail1">Assigned Users</label>
                {{ case_form.assigned_to }}
              </div>
            </div>
            <div class="filter_col col-md-6">
              <div class="form-group">
                <label for="exampleInputEmail1">Teams</label>
                {{ case_form.teams }}
              </div>
            </div>
            <br clear="all">
          </div>
        </div>
      </div>
      <br clear="all">
    </div>
    <div class="overview_form_block row marl">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Overview
          </div>
          <div class="panel-content">
            <div class="row marl">
              <div class="col-md-6">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_name" class="required">Name</label>
                    {{ case_form.name }}
                    <span>{{ case_form.name.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_status" class="required">Status</label>
                    {{ case_form.status }}
                    <span>{{ case_form.status.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_priority" class="required">Priority</label>
                    {{ case_form.priority }}
                    <span>{{ case_form.priority.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_case_type">Type of Case</label>
                    {{ case_form.case_type }}
                    <span>{{ case_form.case_type.errors }}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="exampleInputEmail1" class="required">Close Date</label>
                    <div class='input-group date' id='datepicker1'>
                      {{ case_form.closed_on }}
                      <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                      </span>
                    </div>
                    <span>{{ case_form.closed_on.errors }}</span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_account">Account</label>
                    {{ case_form.account }}
                    <span> {{case_form.account.errors}}</span>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_contacts">Contacts</label>
                    {{ case_form.contacts }}
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label for="id_description">Description</label>
                    {{ case_form.description }}
                    <span>{{ case_form.description.errors }}</span>
                  </div>
                </div>
              </div>
            </div>
            <br clear="all">
          </div>
        </div>
      </div>
      <br clear="all">
      <input type="hidden" id="save_new_form" name="savenewform">
    </div>
    <div class="row marl buttons_row text-center">
      <button class="btn btn-default save" type="submit">Save</button>
      {% if not case_obj %}
        <button class="btn btn-success save savenew" type="submit">Save & New</button>
      {% endif %}
      <a href="{% url 'cases:list' %}" class="btn btn-default">Cancel</a>
    </div>
  </form>
{% endblock %}
{% block js_block %}
  <script src="{% static 'js/cases/create_case.js' %}"></script>
  <script type="text/javascript">
    $(function () {
     var date = new Date();
     var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
      $('#datepicker1').datetimepicker({
          'format': 'YYYY-MM-DD',
          minDate: today
      }).attr('readonly', 'true')
    });

    $(".savenew").on('click', function(e){
      e.preventDefault()
      $("#save_new_form").val('true')
      $('#submitForm').submit()
    });
  </script>
{% endblock js_block %}

templates/cases/sel_contacts.html
<select>
{% for con in con %}
	<option value="{{con.id}}" {% for sel in selcon %}
		{% ifequal con.id sel.id %}
		selected {% endifequal%}{% endfor %}>{{con.name}}</option>
		}
	{% endfor %}
</select>

templates/cases/view_contacts.html
{% for c in contacts %}
	<div class="field case_contacts" data-name="name">{{c.name}}</div>
{% endfor %}