accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'


urlpatterns = [
    url(r'^list/$', views.accounts_list, name='list'),
    url(r'^create/$', views.add_account, name='new_account'),
    url(r'^(?P<account_id>\d*)/view/$', views.view_account, name="view_account"),
    url(r'^(?P<edid>\d*)/edit/$', views.edit_account, name="edit_account"),
    url(r'^(?P<aid>\d*)/delete/$', views.remove_account, name="remove_account"),
    url(r'^get/list/$', views.get_accounts, name='get_accounts'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

contacts/urls.py
from django.conf.urls import url
from contacts import views

app_name = 'contacts'


urlpatterns = [
    url(r'^list/$', views.contacts_list, name='list'),
    url(r'^create/$', views.add_contact, name='add_contact'),
    url(r'^(?P<contact_id>\d+)/view/$', views.view_contact, name='view_contact'),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_contact, name='edit_contact'),
    url(r'^(?P<pk>\d+)/delete/$', views.remove_contact, name='remove_contact'),
    url(r'^get/list/$', views.get_contacts, name='get_contacts'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings

app_name = 'crm'


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^leads/', include('leads.urls', namespace='leads')),
    url(r'^contacts/', include('contacts.urls', namespace='contacts')),
    url(r'^oppurtunities/', include('oppurtunity.urls', namespace='oppurtunities')),
    url(r'^cases/', include('cases.urls', namespace='cases')),
    url(r'^quotations/', include('quotations.urls', namespace='quotations')),
    url(r'^excel/', include('excel.urls', namespace='excel')),
    # url(r'^emails/', include('emails.urls', namespace='emails')),
    # url(r'^planner/', include('planner.urls', namespace='planner')),
    url(r'^logout/$', views.logout, {'next_page': '/login/'}, name='logout'),

]
'''
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
'''

cases/models.py
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from accounts.models import Account
from contacts.models import Contact
from common.models import User, Team
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE


class Case(models.Model):
    name = models.CharField(
        pgettext_lazy("Name of the case", "Name"),
        max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(choices=CASE_TYPE, max_length=255, blank=True, null=True, default='')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_on = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='case_assigned_users')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='case_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting", status="Planned")

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting").exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Task", status="Planned")

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task").exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type, object_id=self.id, event_type="Call", status="Planned")

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call").exclude(status="Planned")

    def get_assigned_user(self):
        return User.objects.get(id=self.assigned_to.id)

common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

from common.utils import COUNTRIES


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', ]

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def __unicode__(self):
        return self.email


class Address(models.Model):
    address_line = models.CharField(_("Address"), max_length=255, blank=True, null=True)
    street = models.CharField(_("Street"), max_length=55, blank=True, null=True)
    city = models.CharField(_("City"), max_length=255, blank=True, null=True)
    state = models.CharField(_("State"), max_length=255, blank=True, null=True)
    postcode = models.CharField(_("Post/Zip-code"), max_length=64, blank=True, null=True)
    country = models.CharField(max_length=3, choices=COUNTRIES, blank=True, null=True)

    def __str__(self):
        return self.city


class Team(models.Model):
    name = models.CharField(max_length=55)
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Comment(models.Model):
    case = models.ForeignKey('cases.Case', blank=True, null=True, related_name="cases", on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    commented_on = models.DateTimeField(auto_now_add=True)
    commented_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    account = models.ForeignKey(
        'accounts.Account', blank=True, null=True, related_name="accounts_comments", on_delete=models.CASCADE)
    lead = models.ForeignKey('leads.Lead', blank=True, null=True, related_name="leads", on_delete=models.CASCADE)
    opportunity = models.ForeignKey(
        'oppurtunity.Opportunity', blank=True, null=True, related_name="opportunity_comments", on_delete=models.CASCADE)
    contact = models.ForeignKey(
        'contacts.Contact', blank=True, null=True, related_name="contact_comments", on_delete=models.CASCADE)

    def get_files(self):
        return Comment_Files.objects.filter(comment_id=self)


class Comment_Files(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now_add=True)
    comment_file = models.FileField("File", upload_to="comment_files", default='')

    def get_file_name(self):
        if self.comment_file:
            return self.comment_file.path.split('/')[-1]
        else:
            return None

contacts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from accounts.models import Account
from common.models import Address, User, Team


class Contact(models.Model):
    first_name = models.CharField(_("First name"), max_length=255)
    last_name = models.CharField(_("Last name"), max_length=255)
    account = models.ForeignKey(Account, related_name='lead_account_contacts', on_delete=models.CASCADE, blank=True, null=True)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    address = models.ForeignKey(Address, related_name='adress_contacts', on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name='contact_assigned_users')
    teams = models.ManyToManyField(Team)
    created_by = models.ForeignKey(User, related_name='contact_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.first_name

contacts/forms.py
from django import forms
from contacts.models import Contact
from common.models import Comment


class ContactForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        contact_account = kwargs.pop('account', [])
        super(ContactForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['description'].widget.attrs.update({
            'rows': '6'})
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['account'].queryset = contact_account
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False

    class Meta:
        model = Contact
        fields = (
            'assigned_to', 'teams', 'first_name', 'last_name', 'account', 'email', 'phone', 'address', 'description'
        )

    def clean_phone(self):
        client_phone = self.cleaned_data.get('phone', None)
        try:
            if int(client_phone) and not client_phone.isalpha():
                ph_length = str(client_phone)
                if len(ph_length) < 10 or len(ph_length) > 13:
                    raise forms.ValidationError('Phone number must be minimum 10 Digits and maximum of 13 Digits')
        except (ValueError):
            raise forms.ValidationError('Phone Number should contain only Numbers')
        return client_phone


class ContactCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'contact', 'commented_by')

templates/contacts/contacts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block content %}
<!-- main_container starts here -->
<div class="main_container">
  <!-- heading_create starts here -->
  <div class="row marl heading_create">
    <div class="heading col-md-12">
      <div class="col-md-6">
        <h4>Contacts</h4>
      </div>
      <div class="col-md-6">
        <div class="create_new text-right">
          <a href="{% url 'contacts:add_contact'%}"><i class="fa fa-plus"></i> Add New Contact</a>
        </div>
      </div>
    </div>
  </div>
  <!-- heading_create ends here -->
  <!-- filter_row starts here -->
  <div class="filter_row row marl">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
        </div>
        <form id="contacts_filter" action="" method="POST">{%csrf_token%}
          <div class="panel-content text-center">
            <div class="filter_col col-md-4">
              <div class="form-group">
                <label for="exampleInputEmail1">ACCOUNTS</label>
                <select class="form-control" id="id_account" name="account">
                  <option value="" selected="selected">--Select an Account--</option>
                  {% for account in accounts %}
                  <option value="{{account.id}}" {%ifequal account.id request.POST.account|add:"0"%} selected {%endifequal%}>{{ account.name }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="filter_col col-md-4">
              <div class="form-group">
                <label for="exampleInputEmail1">NAME</label>
                <input type="text" class="form-control" placeholder="First Name" name="first_name" value="{{request.POST.first_name}}">
              </div>
            </div>
            <div class="filter_col col-md-4">
              <div class="form-group">
                <label for="exampleInputEmail1">CITY</label>
                <input type="text" class="form-control" placeholder="City" name="city" value="{{request.POST.city}}">
              </div>
            </div>
            <div class="filter_col text-center">
              <div class="form-group">
                <button  class="btn btn-primary" type="submit">Search</button>
                <a href="{% url 'contacts:list' %}" class="btn btn-default">Clear</a>
              </div>
            </div>
          </div>
        </form>
        <br clear="all">
      </div>
    </div>
  </div>
  <!-- filter_row ends here -->
  <!-- contacts list start -->
  <div class="table_container_row row marl">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading-list text-center">
          LIST OF CONTACTS
          <span class="pull-right total_count">{% if show_pageitems %} {% show_pageitems %}{% else %}Total Contacts {{contact_obj_list|length}}{% endif %}</span>
        </div>
        <div class="panel-content">
          <table class="table table-bordered table-striped table-condensed">
            <thead>
              <tr>
                <th width="5%" style="text-align:center;">S.No</th>
                <th width="20%" style="text-align:center;">NAME</th>
                <th width="20%" style="text-align:center;">ACCOUNT</th>
                <th width="15%" style="text-align:center;">CITY</th>
                <th width="15%" style="text-align:center;">STATE</th>
                <th width="25%" style="text-align:center;">ACTIONS</th>
              </tr>
            </thead>
            <tbody>
              {% if per_page %}
                {% paginate per_page contact_obj_list %}
              {% else%}
                {% paginate 10 contact_obj_list %}
              {% endif %}
              {% for contact in contact_obj_list %}
              <tr style="text-align:center;">
                <td scope="row">{{ forloop.counter }}</td>
                <td><a href="{% url 'contacts:view_contact' contact.id %}">{{contact.first_name}}</a></td>
                <td>
                  {% if contact.account %}
                    <a href="{% url 'accounts:view_account' contact.account.id %}">{{contact.account}}</a>
                  {% else %}
                    No Related Account
                  {% endif %}
                </td>
                <td>
                  {% if contact.address.city %}
                    {{contact.address.city}}
                  {% else %}
                    Not Specified
                  {% endif %}
                </td>
                <td>
                  {% if contact.address.state %}
                    {{contact.address.state}}
                  {% else %}
                    Not Specified
                  {% endif %}
                </td>
                <td>
                  <a href="{% url 'contacts:view_contact' contact.id %}" class="btn btn-info">View</a>
                  <a href="{% url 'contacts:edit_contact' contact.id%}" class="btn btn-success">Edit</a>
                  <a href="{% url 'contacts:remove_contact' contact.id %}" class="btn btn-danger delete">Delete</a>
                </td>
              </tr>
              {% endfor%}
            </tbody>
          </table>
          {%ifequal contact_obj_list|length 0 %}
            <h4 class="text-center">No Contact Records Found</h4>
          {%endifequal%}
          <div class="marl row text-center">
            {% show_pages %}
          </div>
        </div>
      </div>
    </div>
    <br clear="all">
  </div>
  <!-- contacts list end -->
</div>
<!-- main_container ends here -->
{%endblock%}
{% block js_block %}
<script type="text/javascript">
  $('.delete').click(function(e){
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });

  $("a[rel='page']").click(function(e){
    e.preventDefault();
    $('#contacts_filter').attr("action", $(this).attr("href"));
    $('#contacts_filter').submit();
  });
</script>
{% endblock js_block %}

templates/contacts/contacts_list.html
<table class="table">
    <thead>
    <tr>
        <th width="50%">
            <a href='#'>
                Name
            </a>
            <span class="caret"></span>
        </th>
        <th>
            <a href="#">
                Email
            </a>
        </th>
    </tr>
    </thead>
    <tbody>
    {% ifequal contacts|length  0 %}
     <tr>
         <td class="cell">
         NO CONTACTS FOUND!!
         </td>
     </tr>
    {% endifequal %}
    {% for contact in contacts %}
    <tr>
        <td class="cell">
            <a class="cell parentname" id="{{ contact.id }}">
                {{ contact.name }}
            </a>
        </td>
        <td class="cell parentemail">
            {{ contact.email }}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

templates/contacts/view_contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'contacts:list' %}">Contacts</a></li>
  <li class="active">view</li>
</ol>
{%endblock%}
{%block content%}
<!-- CONTACTS VIEW STARTS -->
  <div class="main_container" id="maincontainer">
    <div class="overview_form_block row marl">
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading view-pad">
            <h5>
              OVERVIEW
              <span class="pull-right" style="margin-top: -10px">
                <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Actions
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'contacts:edit_contact' contact_record.id %}">Edit</a></li>
                    <li class="delete_contact" ><a href="{% url 'contacts:remove_contact' contact_record.id %}" id="remove_contact">REMOVE</a></li>
                  </ul>
                </div>
              </span>
            </h5>
          </div>
          <div class="panel-content" id="datashow">
            <div class="row marl">
              <div class="col-md-6">
                <div class="filter_col col-md-12" id="iname">
                  <div class="form-group" >
                    <label class="contact_field_label" for="id_name" data-name="name">Name</label>
                    <div class="contact_field" id="contact_name" data-name="name">{{ contact_record.first_name }} {{ contact_record.last_name }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_contact_account" data-name="name">Account</label>
                    <div class="contact_field" id ="contact_account" data-name="name">{{ contact_record.account }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_phone" data-name="name">Phone</label>
                    <div class="contact_field" id="contact_phone" data-name="name">{{ contact_record.phone }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="contact_field_label" for="id_email" data-name="name">Email</label>
                    <div class="contact_field" id="contact_email" data-name="name">{{ contact_record.email }}</div>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    {% if contact_record.address.address_line or contact_record.address.street or contact_record.address.city or  contact_record.address.state or contact_record.address.postcode or contact_record.address.country %}
                    <label class="contact_field_label" for="id_address" data-name="name" >Billing Address</label>
                    <div class="contact_field" id="contact_address" data-name="name">
                      {% if contact_record.address.address_line %}
                        Address Line:{{contact_record.address.address_line}}</br>
                      {% endif %}
                      {% if contact_record.address.street %}
                        Street:{{ contact_record.address.street }}</br>
                      {% endif %}
                      {% if contact_record.address.city %}
                        City: {{ contact_record.address.city }}</br>
                      {% endif %}
                      {% if contact_record.address.state %}
                        State:{{ contact_record.address.state }}</br>
                      {% endif %}
                      {% if contact_record.address.postcode %}
                        Post Code:{{ contact_record.address.postcode }}</br>
                      {% endif %}
                      {% if contact_record.address.country %}
                        Country: {{ contact_record.address.get_country_display }}
                      {% endif %}
                    </div>
                    {% endif %}
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    {% if contact_record.description %}
                    <label class="contact_field_label" for="id_description" data-name="name">Description</label>
                    <div class="contact_field" id="contact_description" data-name="name">{{ contact_record.description }}</div>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Comments Section starts-->
          <div class="panel-heading view-pad">
            <h5>COMMENTS</h5>
          </div>
          <div class="panel-content" id="datashow">
            <div class="row marl">
              <div class="col-md-12">
                <form id="comment_form" method="POST" enctype="multipart/form-data">{% csrf_token %}
                  <div class="form-group">
                    <textarea class="form-control" textarea cols="40" rows="3" id="id_comments" name="comment" placeholder="Submit Your Comments Here"></textarea><span><i id="CommentError" style="display:none; color:red"></i></span>
                    </br>
                    <button class="btn btn-default save" style="text-align: center;" id="comment_submit" type="submit">Submit</button>
                  </div>
                  <input type="hidden" value="{{contact_record.id}}" name="contactid">
                </form>
                <ul class="list-group" id="comments_div">
                  {% for comment in comments %}
                  <li class="list-group-item list-row" id="comment{{comment.id}}">
                    <div class="pull-right right-container">
                      <div class="list-row-buttons btn-group pull-right">
                        <button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" type="button"><span class="caret"></span></button>
                        <ul class="dropdown-menu pull-right">
                          <li>
                            <a class="action" onclick="edit_comment({{comment.id}})">Edit</a>
                          </li>
                          <li>
                            <a class="action" onclick="remove_comment({{comment.id}})">Remove</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="stream-head-container">{{ comment.commented_by }} Commented</div>
                    <div class="stream-post-container" id="comment_name{{comment.id}}"><pre>{{ comment.comment }}</pre></div>
                    <div class="stream-date-container">{{ comment.commented_on }}</div>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            <div class="modal fade" id="Comments_Contacts_Modal" role="dialog" data-keyboard="false" data-backdrop="static">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Update Your Comment</h4>
                  </div>
                  <form id="comment_edit_form" method="POST" >{% csrf_token %}
                    <div class="modal-body">
                      <div class="form-group">
                        <textarea class="form-control" textarea cols="40" rows="3" id="id_editcomment" name="comment" placeholder="Submit Your Comments"></textarea>
                        <input type="hidden" value="{{ contact.id }}" name="contactid">
                        <input type="hidden" value="" name="commentid" id="commentid">
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button class="btn btn-default save" id="comment_edit" type="submit">Update</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <!-- Comments Section Ends-->
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading view-pad">
            <h5>Label</h5>
          </div>
          <div class="panel-content" id="datashow">
            <div class="row marl">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_assigned_user" data-name="name">Assigned User(s)</label>
                  <div class="contact_field" id="contact_assigned_users" data-name="name">
                    {%if not contact_record.assigned_to %}
                      Not Assigned Yet
                    {% else %}
                      {% for user in contact_record.assigned_to.all %}
                        <li>{{ user }}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_team" data-name="name">Assigned Team(s)</label>
                  <div class="contact_field" id="contact_team" data-name="name">
                    {%if not contact_record.teams %}
                      Not Assigned Yet
                    {% else %}
                      {% for team in contact_record.teams.all %}
                        <li>{{ team }}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_created_on" data-name="name">Created On</label>
                  <div class="contact_field" id="contact_created_on" data-name="name">
                    {{ contact_record.created_on }}
                  </div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_created_by" data-name="name">Created by</label>
                  <div class="contact_field" id="contact_created_by" data-name="name">
                   {{ contact_record.created_by }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- CONTACTS VIEW ENDS -->
{% endblock%}
{% block js_block %}
  <script src="{% static 'js/contacts/view_contact.js' %}"></script>
{% endblock js_block %}